// Code generated by SQLBoiler 4.14.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Messages string
	Rooms    string
	Users    string
}{
	Messages: "messages",
	Rooms:    "rooms",
	Users:    "users",
}
