// Code generated by SQLBoiler 4.14.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

// This test suite runs each operation test in parallel.
// Example, if your database has 3 tables, the suite will run:
// table1, table2 and table3 Delete in parallel
// table1, table2 and table3 Insert in parallel, and so forth.
// It does NOT run each operation group in parallel.
// Separating the tests thusly grants avoidance of Postgres deadlocks.
func TestParent(t *testing.T) {
	t.Run("Messages", testMessages)
	t.Run("Rooms", testRooms)
	t.Run("Users", testUsers)
}

func TestDelete(t *testing.T) {
	t.Run("Messages", testMessagesDelete)
	t.Run("Rooms", testRoomsDelete)
	t.Run("Users", testUsersDelete)
}

func TestQueryDeleteAll(t *testing.T) {
	t.Run("Messages", testMessagesQueryDeleteAll)
	t.Run("Rooms", testRoomsQueryDeleteAll)
	t.Run("Users", testUsersQueryDeleteAll)
}

func TestSliceDeleteAll(t *testing.T) {
	t.Run("Messages", testMessagesSliceDeleteAll)
	t.Run("Rooms", testRoomsSliceDeleteAll)
	t.Run("Users", testUsersSliceDeleteAll)
}

func TestExists(t *testing.T) {
	t.Run("Messages", testMessagesExists)
	t.Run("Rooms", testRoomsExists)
	t.Run("Users", testUsersExists)
}

func TestFind(t *testing.T) {
	t.Run("Messages", testMessagesFind)
	t.Run("Rooms", testRoomsFind)
	t.Run("Users", testUsersFind)
}

func TestBind(t *testing.T) {
	t.Run("Messages", testMessagesBind)
	t.Run("Rooms", testRoomsBind)
	t.Run("Users", testUsersBind)
}

func TestOne(t *testing.T) {
	t.Run("Messages", testMessagesOne)
	t.Run("Rooms", testRoomsOne)
	t.Run("Users", testUsersOne)
}

func TestAll(t *testing.T) {
	t.Run("Messages", testMessagesAll)
	t.Run("Rooms", testRoomsAll)
	t.Run("Users", testUsersAll)
}

func TestCount(t *testing.T) {
	t.Run("Messages", testMessagesCount)
	t.Run("Rooms", testRoomsCount)
	t.Run("Users", testUsersCount)
}

func TestHooks(t *testing.T) {
	t.Run("Messages", testMessagesHooks)
	t.Run("Rooms", testRoomsHooks)
	t.Run("Users", testUsersHooks)
}

func TestInsert(t *testing.T) {
	t.Run("Messages", testMessagesInsert)
	t.Run("Messages", testMessagesInsertWhitelist)
	t.Run("Rooms", testRoomsInsert)
	t.Run("Rooms", testRoomsInsertWhitelist)
	t.Run("Users", testUsersInsert)
	t.Run("Users", testUsersInsertWhitelist)
}

// TestToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestToOne(t *testing.T) {
	t.Run("MessageToUserUsingUser", testMessageToOneUserUsingUser)
	t.Run("MessageToRoomUsingRoom", testMessageToOneRoomUsingRoom)
}

// TestOneToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOne(t *testing.T) {}

// TestToMany tests cannot be run in parallel
// or deadlocks can occur.
func TestToMany(t *testing.T) {
	t.Run("RoomToMessages", testRoomToManyMessages)
	t.Run("UserToMessages", testUserToManyMessages)
}

// TestToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneSet(t *testing.T) {
	t.Run("MessageToUserUsingMessages", testMessageToOneSetOpUserUsingUser)
	t.Run("MessageToRoomUsingMessages", testMessageToOneSetOpRoomUsingRoom)
}

// TestToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneRemove(t *testing.T) {}

// TestOneToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneSet(t *testing.T) {}

// TestOneToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneRemove(t *testing.T) {}

// TestToManyAdd tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyAdd(t *testing.T) {
	t.Run("RoomToMessages", testRoomToManyAddOpMessages)
	t.Run("UserToMessages", testUserToManyAddOpMessages)
}

// TestToManySet tests cannot be run in parallel
// or deadlocks can occur.
func TestToManySet(t *testing.T) {}

// TestToManyRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyRemove(t *testing.T) {}

func TestReload(t *testing.T) {
	t.Run("Messages", testMessagesReload)
	t.Run("Rooms", testRoomsReload)
	t.Run("Users", testUsersReload)
}

func TestReloadAll(t *testing.T) {
	t.Run("Messages", testMessagesReloadAll)
	t.Run("Rooms", testRoomsReloadAll)
	t.Run("Users", testUsersReloadAll)
}

func TestSelect(t *testing.T) {
	t.Run("Messages", testMessagesSelect)
	t.Run("Rooms", testRoomsSelect)
	t.Run("Users", testUsersSelect)
}

func TestUpdate(t *testing.T) {
	t.Run("Messages", testMessagesUpdate)
	t.Run("Rooms", testRoomsUpdate)
	t.Run("Users", testUsersUpdate)
}

func TestSliceUpdateAll(t *testing.T) {
	t.Run("Messages", testMessagesSliceUpdateAll)
	t.Run("Rooms", testRoomsSliceUpdateAll)
	t.Run("Users", testUsersSliceUpdateAll)
}
